title: ' '
views:
  - title: Audio
    icon: mdi:volume-high
    cards:           
      - type: entities
        title: ' '
        show_header_toggle: false
        show_state: false
        column_width: 100%
        entities:
          - entity: input_select.which_device
            name: Which Device?  
          - entity: input_number.echo_volume
            name: Volume            
          - entity: input_text.announce
            name: Announce            
          - entity: input_select.genre
            name: Genre
          - entity: input_text.artist_song
            name: Artist or Song
          - entity: input_text.artist_radio
            name: Artist Radio
          - entity: input_boolean.stop_music
            name: Stop Music
            icon: mdi:stop
            tap_action: toggle
          - entity: input_boolean.next_song
            name: Next Song
            icon: mdi:skip-forward
            tap_action: toggle            
          - entity: input_boolean.previous_song
            name: Previous Song
            icon: mdi:skip-backward
            tap_action: toggle                    
          - entity: sensor.artist_playing
            name: Artist Playing
            icon: mdi:play     
          - entity: sensor.song_playing
            name: Song Playing
            icon: mdi:play        
