homeassistant:
  customize_glob:
    "sensor.media*":
    hidden: true
    
group:
 alexa:
    name: Alexa Media
    control: hidden
    entities:
     - input_select.which_device
     - input_number.echo_volume
     - input_text.announce
     - input_select.genre
     - input_text.artist_song
     - input_text.artist_radio
     - input_boolean.stop_music
     - input_boolean.next_song
     - input_boolean.previous_song
     - sensor.artist_playing
     - sensor.song_playing

input_boolean:
  stop_music:
    name: Stop Music
    icon: mdi:stop
    initial: off
  next_song:
    name: Next Song
    icon: mdi:skip-next
    initial: off
  previous_song:
    name: Previous Song
    icon: mdi:skip-previous
    initial: off

input_number:
  echo_volume:
    name: Volume
    initial: 10
    min: 5
    max: 10
    step: 0.5
    mode: slider

input_select:
  genre:
    name: Genre
    options:
     - Choose...
     - Easy Pop
     - Top Pop
     - Top Pop (Clean)
     - Top Country
     - Top Country (Clean)
     - Classic Country
     - 80s Rock
     - Top Rock
     - Hard Rock
     - Classic Rock
     - Top Alternative
     - 90s Alternative & Grunge
     - Top Dance
     - Chill Electronic
     - Top Christian
     - Praise & Worship
     - Top Hip Hop
     - Cool Jazz
     - All Blues
     - Oldies
     - All 50s
     - All 60s
     - All 70s
     - All 80s
     - All 90s
     - All 2000s
     - All 2010s
     - Toddler Time
     - Stand-up Comedy
    initial: Choose...
  which_device:
    name: Which Device?
    options:
     - Choose...
     - Kitchen
     - Living Room
     - Bedroom
     - All
    initial: Choose...
   
input_text:    
  announce:
    name: Announce
    icon: mdi:message-alert-outline
    initial: ""      
  artist_song:
    name: Artist/Song
    icon: mdi:music-circle-outline
    initial: ""
  artist_radio:
    name: Station
    icon: mdi:radio
    initial: ""

  
media_player:
  - platform: alexa
    email: !secret alexa_email
    password: !secret alexa_password
    url: amazon.com
    scan_interval: 30    

sensor:
  - platform: template
    sensors:   
     media_kitchen_artist:
      friendly_name: 'kitchen artist'
      value_template: '{{ states.media_player.kitchen_echo.attributes.media_artist }}'      
     media_kitchen_title:
      friendly_name: 'kitchen title'
      value_template: '{{ states.media_player.kitchen_echo.attributes.media_title }}'   
     media_living_artist:
      friendly_name: 'living artist'
      value_template: '{{ states.media_player.living_room.attributes.media_artist }}'      
     media_living_title: 
      friendly_name: 'living title'
      value_template: '{{ states.media_player.living_room.attributes.media_title }}'
     media_bedroom_artist:
      friendly_name: 'bedroom artist'
      value_template: '{{ states.media_player.bedroom_echo.attributes.media_artist }}'      
     media_bedroom_title: 
      friendly_name: 'bedroom title'
      value_template: '{{ states.media_player.bedroom_echo.attributes.media_title }}'
     media_downstairs_artist:
      friendly_name: 'downstairs artist'
      value_template: '{{ states.media_player.downstairs.attributes.media_artist }}'      
     media_downstairs_title: 
      friendly_name: 'downstairs title'
      value_template: '{{ states.media_player.downstairs.attributes.media_title }}'
  - platform: mqtt
    name: Artist Playing
    icon: mdi:speaker-wireless
    state_topic: "alexa/artistplaying"
  - platform: mqtt
    name: Song Playing
    icon: mdi:speaker-wireless
    state_topic: "alexa/songplaying"
    