media_player:
  - platform: alexa
    email: !secret alexa_email
    password: !secret alexa_password
    url: amazon.com
    scan_interval: 30
    

input_select:
  genre:
    name: Genre
    options:
     - Choose...
     - Top Pop (Clean)
     - Classic Rock
     - Top Rock
     - Best of Prime Music
     - Cool Jazz
     - Oldies
    initial: Choose...
  which_device:
    name: Which Device?
    options:
     - Choose...
     - Kitchen
     - Living Room
     - Bedroom
     - All
    initial: Choose...
      
input_boolean:
  stop_music:
    name: Stop Music
    initial: off
  next_song:
    name: Next Song
    initial: off
  previous_song:
    name: Previous Song
    initial: off
    
input_text:
  announce:
    name: Announce
    initial: ""      
  artist_song:
    name: Artist or Song
    initial: ""
  artist_radio:
    name: Artist Radio
    initial: ""
  artist_playing:
    name: Artist
    initial: ""
  song_playing:
    name: Song
    initial: ""
  
input_number:
  echo_volume:
    name: Volume
    initial: 10
    min: 5
    max: 10
    step: 0.5
    mode: slider

sensor:
   kitchen_artist:
    friendly_name: 'kitchen artist'
    value_template: '{{ states.media_player.kitchen_echo.attributes.media_artist }}'      
   kitchen_title:
    friendly_name: 'kitchen title'
    value_template: '{{ states.media_player.kitchen_echo.attributes.media_title }}'   
   living_artist:
    friendly_name: 'living artist'
    value_template: '{{ states.media_player.living_room.attributes.media_artist }}'      
   living_title: 
    friendly_name: 'living title'
    value_template: '{{ states.media_player.living_room.attributes.media_title }}'
   bedroom_artist:
    friendly_name: 'bedroom artist'
    value_template: '{{ states.media_player.bedroom_echo.attributes.media_artist }}'      
   bedroom_title: 
    friendly_name: 'bedroom title'
    value_template: '{{ states.media_player.bedroom_echo.attributes.media_title }}'
   downstairs_artist:
    friendly_name: 'downstairs artist'
    value_template: '{{ states.media_player.downstairs.attributes.media_artist }}'      
   downstairs_title: 
    friendly_name: 'downstairs title'
    value_template: '{{ states.media_player.downstairs.attributes.media_title }}'
    
