homeassistant:
  customize:
## Hide Switches for Node Red Alexa Temperature Announcements 
    input_boolean.downstairs_temp:
      hidden: true
    input_boolean.downstairs_humidity:
      hidden: true
    input_boolean.garage_temp:
      hidden: true
    input_boolean.garage_humidity:
      hidden: true
    input_boolean.upstairs_temp:
      hidden: true
    input_boolean.upstairs_humidity:
      hidden: true  
## Hide rounded temp/humidty sensors alexa uses for announcements
    sensor.upstairs_temp_rounded:
      hidden: true
    sensor.upstairs_humidity_rounded:
      hidden: true
    sensor.downstairs_temp_rounded:
      hidden: true
    sensor.downstairs_humidity_rounded:
      hidden: true
    sensor.garage_temp_rounded:
      hidden: true
    sensor.garage_humidity_rounded:
      hidden: true

     
## Switches for Node Red Alexa Temperature Announcements     
input_boolean:
  downstairs_temp:
    name: Downstairs Temperature
    initial: off
  downstairs_humidity:
    name: Downstairs Humidity
    initial: off    
  garage_temp:
    name: Garage Temperature
    initial: off
  garage_humidity:
    name: Garage Humidity
    initial: off
  upstairs_temp:
    name: Upstairs Temperature
    initial: off
  upstairs_humidity:
    name: Upstairs Humidity
    initial: off
    
sensor:
## Downstairs Climate Sensors        
  - platform: mqtt
    state_topic: 'tele/downstairs_climate/SENSOR'
    name: 'Downstairs Temp' #AM2302
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature | float - 1 }}'
  - platform: mqtt
    state_topic: 'tele/downstairs_climate/SENSOR'
    name: 'Downstairs Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'

## Downstairs Rounded Climate Sensors For Alexa Announcements In Node Red    
  - platform: template
    sensors:
      downstairs_temp_rounded:
        value_template: "{{ states('sensor.downstairs_temp') | round(0) }}"
      downstairs_humidity_rounded:
        value_template: "{{ states('sensor.downstairs_humidity') | round(0) }}"
        
## Garage Climate Sensors        
  - platform: mqtt
    state_topic: 'tele/garage_light2/SENSOR'
    name: 'Garage Temp' #AM2302
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature | float - 1 }}'
  - platform: mqtt
    state_topic: 'tele/garage_light2/SENSOR'
    name: 'Garage Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'

## Garage Rounded Climate Sensors For Alexa Announcements In Node Red    
  - platform: template
    sensors:
      garage_temp_rounded:
        value_template: "{{ states('sensor.garage_temp') | round(0) }}"
      garage_humidity_rounded:
        value_template: "{{ states('sensor.garage_humidity') | round(0) }}"
        
## Upstairs Climate Sensors
  - platform: mqtt
    state_topic: 'tele/upstairs_climate/SENSOR'
    name: 'Upstairs Temp' #AM2302
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature | float - 1 }}'
  - platform: mqtt
    state_topic: 'tele/upstairs_climate/SENSOR'
    name: 'Upstairs Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'
    
## Upstairs Rounded Climate Sensors For Alexa Announcements In Node Red    
  - platform: template
    sensors:
      upstairs_temp_rounded:
        value_template: "{{ states('sensor.upstairs_temp') | round(0) }}"
      upstairs_humidity_rounded:
        value_template: "{{ states('sensor.upstairs_humidity') | round(0) }}"
        
    

   