homeassistant:
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
  name: ' '
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages:
    alexa: !include alexa.yaml
    climate: !include climate.yaml
